version: '3'
services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./app/:/app
    depends_on:
      - nginx
    environment:
      FLASK_APP : app.py
      FLASK_ENV : development
  db:
    image: postgres:latest
    environment: 
      POSTGRES_USER : user
      POSTGRES_PASSWORD : password
      POSTGRES_DB : db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  cache:
    image: redis:latest
    ports:
      - "6379:6379"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db
    ports:
      - "8080:80"
  