services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./app/:/app
    
    environment:
      FLASK_APP : app.py
      FLASK_ENV : development
  db:
    image: postgres:latest
    environment: 
      POSTGRES_USER : user
      POSTGRES_PASSWORD : password
      POSTGRES_DB : db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data